### ISSUE TITLE
getShipperName() function

### ISSUE THREAD

**Issue by lorro** [picqer/sendcloud-php-client#13]
Hi,

What is your stance about making the getShipperName() function in Parcel.php a public one instead of a private function. The function would be handy for something I would like to develop, but at the moment it's unreachable to my Parcel object as it's a private one :)

Greetings

**Comment by casperbakker** [comment]
HI @lorro,

Sure, sounds fine with me. Could be a useful function indeed.

If you provide a pull request, I will merge it.
