### ISSUE TITLE
How to create parcel with From Address As customer address

### ISSUE THREAD

**Issue by ipehimanshu** [picqer/sendcloud-php-client#29]
How to create parcel with From Address As customer address?

We want from address should be customer address and TO address will be company address?

Thanks

**Comment by casperbakker** [comment]
As far as I know, you cannot do that with the normal shipments endpoint in the Sendcloud API. You can only have a from-address that is a configured address in the Sendcloud portal.

Maybe it is something you can do with the [Return portal API](https://docs.sendcloud.sc/api/v2/return-portal/), but I have not used it myself. 

Maybe Sendcloud's support can help you with how this can be done in the API itself, then you can see how you can do it with this client.
