### ISSUE TITLE
Invalid shipping_method error whene creating a new parcel

### ISSUE THREAD

**Issue by davalb** [picqer/sendcloud-php-client#4]
Hi,

when I try the example from the readme-file `$parcel->shipment = 10;`
I get this error
```
SendCloud error: shipping_method: "Invalid shipping method"
```
Any help much appreciated! Thanks

**Comment by casperbakker** [comment]
You probably do not have access to shipping method number 10. As mentioned in the readme you can retrieve all the valid shipping methods in your account with ```$sendCloud->shippingMethods()->all()```

**Comment by davalb** [comment]
You're right, thanks a lot.
