### ISSUE TITLE
Adding 'quantity' for multi-collo shipments

### ISSUE THREAD

**Issue by gijspouwels** [picqer/sendcloud-php-client#40]
Would it be possible to add a fillable 'quantity' field to the Parcel model, in order to make it possible to [create multi-collo parcels](https://docs.sendcloud.sc/api/v2/shipping/#create-a-parcel). Or is there I downside to this that I don't see? Seems to work when I just edit the object.

I could add it in a fork and make a pull request, but as it seems to be just an extra key to the $fillable array it might be easier to add it to the original code?

**Comment by casperbakker** [comment]
After 3 years, I now merged #49. Thanks for the patience :)
